/**
 * @file bits/crt.h
 * @brief Internal C runtime declarations.
 *
 * This header declares symbols that are internal to the C runtime.
 * They are used by the startup code, by exit(), and by code
 * generated by the compiler (GCC/Clang).
 *
 * Do NOT include this header from user code. Use the public
 * headers (<stdlib.h>, <unistd.h>) instead.
 */

#ifndef _BITS_CRT_H
# define _BITS_CRT_H

# include <bits/os.h>
# include <bits/arch.h>

# if defined(__cplusplus)
extern "C" {
# endif

/**
 * @brief Run all atexit handlers.
 *
 * This function is called by exit() to run all functions registered
 * with atexit().
 */
void	__haj_run_atexit(void);


/* ----- C++ ABI ----- */

/**
 * @brief Register a destructor to run at exit.
 *
 * This is the C++ ABI function for registering destructors that
 * should run at exit. It is also used by GCC for
 * __attribute__((destructor)) on C code compiled with certain
 * flags.
 *
 * The signature is:
 *   int __cxa_atexit(void (*func)(void *), void *arg, void *dso_handle);
 *
 * We do not support the dso_handle for now. We just call func
 * with arg when the process exits.
 */
int	__cxa_atexit(void (*func)(void *), void *arg, void *dso_handle);

/*
 * @brief Finalize a DSO.
 *
 * This function is called when a shared library is unloaded, or
 * when the process exits, to run all destructors registered with
 * __cxa_atexit for that DSO.
 *
 * Since we do not use shared libraries, this is mostly a no-op.
 * It is provided for compatibility with code compiled with
 * GCC/Clang that generates references to it.
 */
void	__cxa_finalize(void *dso_handle);

/*
 * @brief The DSO handle for the main program.
 *
 * __dso_handle is a symbol that GCC/Clang generate references to
 * when compiling code that uses __attribute__((destructor)) or
 * C++ static destructors. It identifies the "current DSO"
 * (dynamic shared object) to __cxa_atexit.
 */
extern void	*__dso_handle;

/**
 * @brief Run all __cxa_atexit handlers.
 *
 * This function is called by __cxa_finalize with NULL to run all
 * handlers.
 */
void	__haj_run_cxa_atexit(void);

# if defined(__cplusplus)
}
# endif

#endif /* _BITS_CRT_H */
